# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e15629ba588c75e9ce24d1a2ee46af1aa893967725fc5834744bb62f298a7272f80a31ee1193b5c3f977b528ee4d7bb40b2765a17d931e832e4bf408431e0ea

test:
  secret_key_base: bbc149f08d7b384bcf22ae8a43c613bffb9fac76f5361ebfc57fed5b0ab65ab0c43b366ef897274cf40f9a7764231da80c1bdf0b0aeb9e341375f93f301d42da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
